name: Mayhem
true:
  pull_request: null
  push: null
  workflow_dispatch: null
env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io
jobs:
  build:
    name: ${{ matrix.os }} shared=${{ matrix.shared }} ${{ matrix.build_type }}
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Log in to the Container registry
      uses: docker/login-action@v2.1.0
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
    - id: meta
      name: Extract metadata (tags, labels) for Docker
      uses: docker/metadata-action@v4.1.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: fuzz/Dockerfile
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
    strategy:
      matrix:
        build_type:
        - Release
        include:
        - os: ubuntu-latest
          triplet: x64-linux
        os:
        - ubuntu-latest
        shared:
        - false
  mayhem:
    name: fuzz ${{ matrix.mayhemfile }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Start analysis for ${{ matrix.mayhemfile }}
      uses: ForAllSecure/mcode-action@v1
      with:
        args: --image ${{ needs.build.outputs.image }} --file ${{ matrix.mayhemfile
          }} --duration 300
        mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
        sarif-output: sarif
    - name: Upload SARIF file(s)
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: sarif
    strategy:
      fail-fast: false
      matrix:
        mayhemfile:
        - fuzz/Mayhemfile_aes_encrypt
